sudo: false
language: ruby
rvm:
  - 2.3.3
before_install:
  - |
    export ENV_DOC=development;
    if [ "$TRAVIS_BRANCH" = 'master' ] || [ -n "$TRAVIS_TAG" ]; then
      export ENV_DOC=production;
    fi
    echo "ENV_DOC: $ENV_DOC";
before_deploy:
  - ./scripts/robots.sh
  - pip install --user awscli  
  - ./scripts/clean_bucket.sh
cache: bundler
script: bundle exec middleman build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET_NAME
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
      tags: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID_DEV
    secret_access_key: $AWS_SECRET_ACCESS_KEY_DEV
    bucket: $AWS_BUCKET_NAME_DEV
    local_dir: build
    skip_cleanup: true
    on:
      branch: develop